clssite/urls.py
from django.contrib import admin
from django.urls import path , include
from .view import redirect_to_gm
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_gm),
    path('gm/',include(('gm_dashboard.urls','gm_dashboard'),namespace="gm") ),
    path('fna/',include(('FnA_dashboard.urls','FnA_dashboard'),namespace="fna") ),
]

gm_dashboard/urls.py
from django.urls import path, include
from .views.dashboard import DashboardIndexView, SheetStatusView, RunSheetScriptView, update_sheet
from django.urls import path, include
from .views.sheets import get_json_sheet,get_winner, IndexView, SummaryView

urlpatterns = [
    path('dashboard/', DashboardIndexView.as_view()),
    path('update_sheet', update_sheet),
    path('dashboard/check_script_status', SheetStatusView.as_view()),
    path('dashboard/run_sheet_script/<sheet>', RunSheetScriptView.as_view()),
    path('', DashboardIndexView.as_view(),name="sheet_compilation"),
    path('sheets/<sheet>', IndexView.as_view(), name='sheet_details'),
    path('sheets/<sheet>/summary', SummaryView.as_view(), name='sheet_summary'),
    path('sheets/<sheet>/summary/get_winner', get_winner, name='sheet_winner'),
    path('sheets/<sheet>/json', get_json_sheet, name='sheet_json'),
]

gm_dashboard/models.py
from django.db import models
from os import environ as env
from datetime import date

class Sheet(models.Model):
    CSV_FILES = [{"display_name": "Actual Vs Quoted", "csv_path": env['STORAGE_DIR'] + 'ActualVSQuoted.csv', "script_path": env['STORAGE_DIR'], "config_name": "actual_vs_quoted"}]
    updated_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    display_name = models.TextField()
    config_name = models.TextField()
    csv_path = models.TextField()
    script_path = models.TextField()
    code = models.TextField()
    TYPE_CHOICES = [
        ('FnA', 'FnA'),
        ('GM', 'GM')
    ]
    sheet_type = models.CharField(max_length=25, choices=TYPE_CHOICES)

    @property
    def is_seen_today(self):
        return date.today() == self.updated_at.date()

class GMManager(models.Manager):
  def get_queryset(self):
    return super().get_queryset().filter(sheet_type='GM')

class GMSheet(Sheet):
  objects = GMManager()

  class Meta:
    proxy = True

gm_dashboard/forms/get_year_data.py
from django import forms
import pdb
from gm_dashboard.models import Sheet

class GetYearData(forms.Form):
    def __init__(self,*args,**kwargs):
        choices = kwargs.pop('choices')
        super(GetYearData,self).__init__(*args,**kwargs)
        CHOICES = []
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        for choice in choices: 
            CHOICES.append((choice, choice))
        self.fields['years'].choices = CHOICES
    years = forms.ChoiceField(required=True, choices=[],label ="Select Year to see yearly data")

gm_dashboard/views/dashboard.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import JsonResponse
from gm_dashboard.models import GMSheet, Sheet
from utils.sheets.process_sheets import ProcessSheets
from django.views.decorators.csrf import csrf_exempt

import time
import pdb

class DashboardIndexView(TemplateView):
    template_name = 'dashboard/index.html'
    def get(self, request):
        sheets = GMSheet.objects.all()
        context = {}
        context["sheets"] = sheets
        res = ProcessSheets().get_process_id()
        if res['status'] == 'running':
            context['running'] = res
        return render(request, self.template_name, context=context )

class SheetStatusView(TemplateView):
    def post(self, request):
        res = ProcessSheets().get_process_id()
        return JsonResponse(res, safe=False)

class RunSheetScriptView(TemplateView):
    def post(self, request, sheet):
        sheet =  GMSheet.objects.get(pk=sheet)
        if sheet:
            res = ProcessSheets().run_script(sheet)
            return JsonResponse(res, safe=False)

@csrf_exempt
def update_sheet(request):
    id = int(request.POST['id'])
    value = (request.POST['value'])
    sheet = Sheet.objects.filter(id=id).update(display_name=value)
    return JsonResponse(sheet, safe=False)

gm_dashboard/views/sheets.py
from django.shortcuts import render
from utils.server_db import query, csv_report_builder
from datetime import datetime
from gm_dashboard.models import GMSheet
from django.views.generic import TemplateView
from django.core import serializers
from django.http import HttpResponse
from gm_dashboard.forms.get_year_data import GetYearData
from pandas import read_csv
from utils.sheets.actual_vs_quoted import ActualVsQuoted
from utils.sheets.context import Context
from utils.sheets.process_sheets import ProcessSheets
import pdb
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
import numpy as np
import functools 
import json
from django.http import JsonResponse

class IndexView(TemplateView):
    def get(self, request, sheet):
        sheet = GMSheet.objects.get(id=sheet)
        context = Context(sheet).get_index_view_context()
        context["sheet"] = sheet
        return render(request, sheet.config_name + "/index.html", context=context )

class SummaryView(TemplateView):

    def get(self, request, sheet):
        GMSheet.objects.filter(id=sheet).update(updated_at=datetime.now())
        sheet = GMSheet.objects.get(id=sheet)
        context =  Context(sheet).get_summary_view_context()
        context["sheet"] = sheet
        return render(request, sheet.config_name + "/summary.html", context=context )
    
    def post(self, request, sheet):
        year = request.POST.get('year')
        data = ActualVsQuoted().get_specific_year_summary_data(year)
        return render(request, "partials/details_year_data.html", context={"key": year, "values" : data.items()} )


class Sheet1SummaryYearlyView(TemplateView):
    template_name = 'sheet1/yearly.html'
    
    def get(self, request, sheet, year):
        data = get_data_from_db_server()
        context = {}
        data = list(filter(lambda x: x[3] == int(year), data))
        context["result_years"] = data
        context["year"] = year
        return render(request, self.template_name, context=context )

def create_yearly_data(data):
    yearl_data = {}
    for row in data:
        if row[3] is not None:
            if row[3] in yearl_data.keys():
                if row[1] > 0:
                    yearl_data[row[3]]["actual"] = yearl_data[row[3]]["actual"] + row[1]
                if row[2] > 0:
                    yearl_data[row[3]]["quoted"] = yearl_data[row[3]]["quoted"] + row[2]
            else:
                yearl_data[row[3]] = {"actual": 0, "quoted": 0}
                if row[1] > 0:
                    yearl_data[row[3]]["actual"] = row[1]
                if row[2] > 0:
                    yearl_data[row[3]]["quoted"] = row[2]
    sorted_data = sort_yearly(yearl_data)
    
    return sorted_data

def get_winner(request, sheet):
    year = request.POST.get('year')
    data = ActualVsQuoted().get_winner_of_year(year)
    return render(request, "partials/get_leader_details.html", context={"values" : data.items()} )

def get_json_sheet(request, sheet):
    offset = int(request.GET['start'])
    limit = int(request.GET['length'])
    page = abs(int(offset/limit + 1))
    data = ActualVsQuoted().get_all_json(request)
    json_data = json.loads(data)
    length = len(json_data["data"])
    paginator = Paginator(json_data["data"], int(limit))
    objects = paginator.page(page)
    list_objs= list(objects)
    res = {
        "draw":  int(request.GET['draw']),
        "recordsTotal": length,
        "recordsFiltered": length,
        "data": list_objs,
    }
    return JsonResponse(res, safe=False)


def sort_yearly(data):
    sorted_data = {}
    for i in sorted(data, reverse=True): 
        sorted_data[i] = data[i]
        sorted_data[i]["ratio"] =round(data[i]["quoted"] / data[i]["actual"], 2)
    sorted_data.popitem()
    sorted_data.popitem()
    sorted_data.popitem()
    return sorted_data

def unique(list1):
    unique_list = []
    for x in list1:
        if x not in unique_list:
            unique_list.append(x)
    return unique_list

gm_dashboard/templates/actual_vs_quoted/index.html
{% extends 'base.html' %}
{% load cache %}
{% load static %}
{% cache 500 content %}
{% block content %} 
<div style="overflow-x:auto;">
   <table class="table table-cls table-bordered" id="example">
       <thead><tr>
           {% for c in columns%}
           <th>{{c}}</th>
           {% endfor %}
       </tr></thead>
       <tbody></tbody>
  </table>
</div>
{% endblock %}
{% block js %}
<script>
    $(document).ready(()=>{
        $('#example thead tr').clone(true).appendTo( '#example thead' );
        $('#example thead tr:eq(0) th').each( function (i) {
            var title = $(this).text();
            $(this).html( '<input type="text" placeholder="Search '+title+'"   id="'+title.split(' ').join('_')+'"/>' );
    
            $( 'input', this ).on( 'keyup change', function () {
                if ( table.column(i).search() !== this.value ) {
                    table
                        .column(i)
                        .search( this.value )
                        .draw();
                }
            } );
        } );
        var table = $('#example').DataTable({
                    processing: true,
                    serverSide: true,
                    "ajax": {
                        url:"/gm/sheets/{{sheet.id}}/json",
                        type: "GET",
                    },
                    initComplete: res => {
                        setTimeout(selectSelectedFilters, 500)
                    }
                });
       $("#example_filter").empty()
       var selectSelectedFilters = () => {
            var vars = {};
            var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value) {
                vars[key] = value;
            });
            for (var key in vars) {
                if (vars.hasOwnProperty(key)) {
                        $("#"+key).val(vars[key]);
                        $("#"+key).trigger("change");
                }
            }
       }  
    })
</script>
{% endblock %}
{% endcache %}

gm_dashboard/templates/actual_vs_quoted/person.html
{% extends 'base.html' %}
{% load cache %}
{% load static %}
{% cache 500 content %}
{% block content %}
<div style="overflow-x:auto;">

    <h1>{{year}}</h1>
     <table class="table table-striped table-bordered">
        <thead>
          <tr>
              <th>Invoice #</th>
              <th>Dispatch #</th>
              <th>Sales Person</th>
              <th>Quoted hours</th>
              <th>Quoted hours bill</th>
              <th>Actual hours</th>
              <th>Week</th>
              <th>Year</th>
              <th>Month</th>
              <th>Day</th>
          </tr>
        </thead>
        <tbody>
        {% for  v in data %}
        <tr>
            {% for col in v%}
                <td>{{col}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
        </tbody>
      </table>
</div>
  
{% endblock %}

{% block js %}
<script>
    $(document).ready(() =>{
        $('.table').DataTable();
    })
</script>
{% endblock %}
{% endcache %}

gm_dashboard/templates/actual_vs_quoted/summary.html
{% extends 'base.html' %}
{% load cache %}
{% load static %}
{% cache 500 content %}
{% block content %}
    <div class="d-flex mb-3 mb-md-4 justify-content-between">
        <h4 class=" sheet_link" data-id="{{sheet.id}}">{{sheet.display_name}}</h4> 
        <a  class="" href="/gm/sheets/{{sheet.id}}">See Full Report</a>
    </div>
    <div class="row">
        <div class="col-md-4">
            <table class="table table-cls table-bordered">
                <thead style="border-bottom: 1px solid black">
                  <tr>
                      <td>Year</td>
                      <td>Quoted</td>
                      <td>Actual</td>
                      <td>Ratio</td>
                  </tr>
                </thead>
                <tbody>
                {% for row in yearly_data %}
                <tr>
                    <td style="margin-right: 4px;"><a href="/gm/sheets/{{sheet.id}}?Year={{row|first}}">{{row| first}}</a></td>
                    <td style="margin-right: 4px;">{{row.1|floatformat }}</td>
                    <td style="margin-right: 4px;">{{row.2|floatformat}}</td>
                    <td style="margin-right: 4px;">{{row.3|floatformat}}</td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
              <form action="" class="mt-2 text-center">
                  {{form}}
              </form>
            <div class="details-year-table">
            </div>
        </div>
        <div class="col-md-4 col-md-4 align-items-center d-flex" style="flex-direction: column;">
            <h6 class="mt-3 primary" style="color: #238fd2">Golden Ratio</h6>
            <table class="table table-cls table-bordered" style="border: 1px solid black">
                <thead>

                    <tr>
                        <td>Estimate/Actual</td>
                        <td>{{golden_ratio.golden_ratio|floatformat}}</td>
                    </tr>
                </thead>
                <tbody>
                    
                    <tr>
                        <td>Target</td>
                        <td>{{golden_ratio.target}}</td>
                    </tr>
                    
                    <tr>
                        <td>Difference</td>
                        <td>{{golden_ratio.difference }}</td>
                    </tr>
                </tbody>
            </table>
            <div class="winner-hours d-flex align-items-center">

            </div>
            <table class="table table-cls table-bordered">
                <thead>
                    <tr>
                    <td></td>
                        {% for row in yearly_data %}
                            <td >{{row.0}}</td>
                        {% endfor %}
                    </tr>
                </thead>
                <tr>
                  <td scope="row" style="border-bottom: 1px solid black">PM</td>
                  <td>%</td>
                  <td>%</td>
                  <td>%</td>
                </tr>
                <tr>
                  <td >External</td>
                  
                  {% for row in yearly_data %}
                  <td >{{row.3|floatformat}}</td>
                {% endfor %}
                </tr>
            </table>
            <table class="table table-cls table-bordered">
                <thead>
                    <tr>
                    <td></td>
                        {% for row in yearly_data %}
                            <td >{{row.0}}</td>
                        {% endfor %}
                    </tr>
                </thead>
                <tr>
                  <td scope="row" style="border-bottom: 1px solid black">Technicians</td>
                  <td>%</td>
                  <td>%</td>
                  <td>%</td>
                </tr>
                <tr>
                  <td >Install</td>
                  
                  {% for row in technicians_average %}
                    <td >{{row|floatformat}}</td>
                    {% endfor %}
                </tr>
            </table>
        </div>
        <div class="col-md-4">
            <h6>Technicians</h6>
            <table  class="table table-cls table-bordered">
                <thead>
                <tr>
                    <td></td>
                    
                    {% for row in years_list %}
                        <td >{{row}}</td>
                    {% endfor %}
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td scope="row" style="border-bottom: 1px solid black">Install Team</td>
                  </tr>
                    
                    {% for row in technicians_list %}
                    <tr>
                        <td >{{row.0}}</td>
                        <td >{{row.1| floatformat}}</td>
                        <td >{{row.2| floatformat}}</td>
                        <td >{{row.3| floatformat}}</td>
                    </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

  
{% endblock %}

{% block js %}
<script>
    $(document).ready(() =>{
        var token = '{{csrf_token}}';
        $('#id_years').on("change", e => {
            $("#loading").show()
            getYearlyDataFromServer(e.target.value)
        });
        var getYearlyDataFromServer = (year) => {
            $.ajax({
                headers: { "X-CSRFToken": token },
                url: window.location.pathname,
                type: "POST",
                data: {year: year.toString()}, 
                success: res => {
                    $('.details-year-table').html(res)
                },
                complete: () => {
                    $("#loading").hide()
                }
            })
        }
        getYearlyDataFromServer("{{first_year}}");
        var getWinnerOfLatestYear = (year) => {
            $.ajax({
                headers: { "X-CSRFToken": token },
                url: "summary/get_winner",
                type: "POST",
                data: {year: year.toString()}, 
                success: res => {
                    debugger
                    $('.winner-hours').html(res)
                },
                complete: () => {
                    $("#loading").hide()
                }
            })
        }
        getWinnerOfLatestYear("{{first_year}}")
    })
</script>
{% endblock %}
{% endcache %}

gm_dashboard/templates/actual_vs_quoted/yearly.html
{% extends 'base.html' %}
{% load cache %}
{% load static %}
{% cache 500 content %}
{% block content %}
<div style="overflow-x:auto;">

    <h1>{{year}}</h1>
     <table class="table table-striped table-bordered">
        <thead>
          <tr>
              <th>PM</th>
              <th>Quoted</th>
              <th>Actual</th>
              <th>Year</th>
              <th>Actions</th>
          </tr>
        </thead>
        <tbody>
        {% for  v in result_years %}
        <tr>
            {% for col in v%}
                <td>{{col}}</td>
            {% endfor %}
            <td><a href="/sheets/actualvsquoted/year/{{v.3}}/person/{% with v|first as first_doc %}{{ first_doc }}{% endwith %}">Details</a></td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
</div>
  
{% endblock %}

{% block js %}
<script>
    $(document).ready(() =>{
        $('.table').DataTable();
    })
</script>
{% endblock %}
{% endcache %}