clssite/urls.py
from django.contrib import admin
from django.urls import path , include
from .view import redirect_to_gm
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_gm),
    path('gm/',include(('gm_dashboard.urls','gm_dashboard'),namespace="gm") ),
    path('fna/',include(('FnA_dashboard.urls','FnA_dashboard'),namespace="fna") ),
]

gm_dashboard/urls.py
from django.urls import path, include
from .views.dashboard import DashboardIndexView, SheetStatusView, RunSheetScriptView, update_sheet
from django.urls import path, include
from .views.sheets import get_json_sheet,get_winner, IndexView, SummaryView

urlpatterns = [
    path('dashboard/', DashboardIndexView.as_view()),
    path('update_sheet', update_sheet),
    path('dashboard/check_script_status', SheetStatusView.as_view()),
    path('dashboard/run_sheet_script/<sheet>', RunSheetScriptView.as_view()),
    path('', DashboardIndexView.as_view(),name="sheet_compilation"),
    path('sheets/<sheet>', IndexView.as_view(), name='sheet_details'),
    path('sheets/<sheet>/summary', SummaryView.as_view(), name='sheet_summary'),
    path('sheets/<sheet>/summary/get_winner', get_winner, name='sheet_winner'),
    path('sheets/<sheet>/json', get_json_sheet, name='sheet_json'),
]

gm_dashboard/models.py
from django.db import models
from os import environ as env
from datetime import date

class Sheet(models.Model):
    CSV_FILES = [{"display_name": "Actual Vs Quoted", "csv_path": env['STORAGE_DIR'] + 'ActualVSQuoted.csv', "script_path": env['STORAGE_DIR'], "config_name": "actual_vs_quoted"}]
    updated_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    display_name = models.TextField()
    config_name = models.TextField()
    csv_path = models.TextField()
    script_path = models.TextField()
    code = models.TextField()
    TYPE_CHOICES = [
        ('FnA', 'FnA'),
        ('GM', 'GM')
    ]
    sheet_type = models.CharField(max_length=25, choices=TYPE_CHOICES)

    @property
    def is_seen_today(self):
        return date.today() == self.updated_at.date()

class GMManager(models.Manager):
  def get_queryset(self):
    return super().get_queryset().filter(sheet_type='GM')

class GMSheet(Sheet):
  objects = GMManager()

  class Meta:
    proxy = True

gm_dashboard/forms/get_year_data.py
from django import forms
import pdb
from gm_dashboard.models import Sheet

class GetYearData(forms.Form):
    def __init__(self,*args,**kwargs):
        choices = kwargs.pop('choices')
        super(GetYearData,self).__init__(*args,**kwargs)
        CHOICES = []
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        for choice in choices: 
            CHOICES.append((choice, choice))
        self.fields['years'].choices = CHOICES
    years = forms.ChoiceField(required=True, choices=[],label ="Select Year to see yearly data")

FnA_dashboard/views/dashboard.py
from django.shortcuts import render
from FnA_dashboard.models import FnaSheet
from django.views.generic import TemplateView
from FnA_dashboard.utils.sheet_data  import SheetData
import pdb
from  utils.server_db import query, update_query
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime
import json
from utils.department.department_info import read_write_department, Department_Data
from gm_dashboard.context_processors import fna_sheets, gm_sheets
from django.core.paginator import Paginator
from utils.server_db import query

class DepartmentDashboard(TemplateView):
    def get(self, request, department_name):
        context = {}
        columns = Department_Data(department_name).get_headers()
        # context["columns"] = columns
        # context["columns_len"] = range(0,len(columns))
        
        context["columns"] = {}
        for c in columns:
            context["columns"][c] = dashboard_datatable(request, c, department_name)

        return render(request, "dashboard.html", context=context )


class DatatableClass():
    def __init__(self, id, name, actual):
        self.id = id
        self.name = name
        self.actual = actual

    def get_obj(self):
        return self


def format_datatable_request(datatables):
    request = {}
    request["draw"] = int(datatables.get('draw')) if datatables.get('draw') else ''
    request["start"] = int(datatables.get('start')) if datatables.get('start') else ''
    request["total"] = int(datatables.get('length')) if datatables.get('length') else ''
    request["ordercol"] = int(datatables.get('order[0][column]')) if datatables.get('order[0][column]') else ''
    request["order"] = datatables.get('order[0][dir]') if datatables.get('order[0][dir]') else ''
    request["reverse"] = request["order"] == "asc"
    return request


def ordering_datatable_response(order_list, formatted_req, request):
    # members_order_list = order_list

    formatted_req["total"] = len(order_list) if formatted_req["total"] == -1 else formatted_req["total"]

    filtered_count = len(order_list)

    # members_order_list = sort_datatable_data(members_order_list, formatted_req, 1, ORDER_COLS_MEMBERS_LISTING)

    members_order_list = order_list[formatted_req["start"]:formatted_req["start"] + formatted_req["total"]]
    paginator = Paginator(members_order_list, formatted_req["total"])
    return [paginator, filtered_count]


def response_dump(paginator, start, draw, total_uses):
    try:
        data = paginator.page(0).object_list
    except:
        data = paginator.page(1).object_list
    resp = {
        "draw": draw,
        "recordsTotal": total_uses,
        "recordsFiltered": total_uses,
        "data": list(data)
    }
    return resp


def dashboard_datatable(request, item_name, department_name):
    context = {}
    columns_name = Department_Data(department_name).get_items(item_name)
    fna = fna_sheets(request)['fna_sheets']
    gm = gm_sheets(request)['gm_sheets']

    fna_display_name = list(fna.values_list('display_name', flat=True))
    fna_display_name = [x.lower() for x in fna_display_name]

    gm_display_name = list(gm.values_list('display_name', flat=True))
    gm_display_name = [x.lower() for x in gm_display_name]
    
    final_list = []
    for item in columns_name:
        if item.lower() in fna_display_name:
            fna_item_index = fna_display_name.index(item.lower())
            sheet_id = fna[fna_item_index].id

            sheet = FnaSheet.objects.get(id=sheet_id)
            res = SheetData(sheet).get_count()
            res = query(res)[0][0]
            # obj = DatatableClass(sheet_id, fna[fna_item_index].display_name, res)
            # final_list.append(obj.get_obj())
            final_list.append({
                'id': sheet_id,
                'display_name': fna[fna_item_index].display_name,
                'actual': res,
                'target': 0,
                'streek': 0
            })

        elif item.lower() in gm_display_name:
            gm_item_index = gm_display_name.index(item.lower())
            final_list.append({
                'id': gm[gm_item_index].id,
                'display_name': gm[gm_item_index].display_name,
                'actual': 0,
                'target': 0,
                'streek': 0
            })
        else:
            final_list.append({
                'id': 0,
                'display_name': item,
                'actual': 0,
                'target': 0,
                'streek': 0
            })

    return final_list

    # formatted_req = format_datatable_request(request.GET)
    # paginator, filtered_count = ordering_datatable_response(final_list, formatted_req, request)
    # return JsonResponse(response_dump(paginator, formatted_req["start"], formatted_req["draw"], filtered_count))


def department_dashboard(department_name):
    context = {}
    sidebar_data = Department_Data(department_name)
    context["headers"], sidebar_data_content, context["department_name"] = sidebar_data.get_sidebar()

    fna = fna_sheets(request)['fna_sheets']
    gm = gm_sheets(request)['gm_sheets']

    fna_display_name = list(fna.values_list('display_name', flat=True))
    fna_display_name = [x.lower() for x in fna_display_name]

    gm_display_name = list(gm.values_list('display_name', flat=True))
    gm_display_name = [x.lower() for x in gm_display_name]

    for key, data in sidebar_data_content.items():
        final_sidebar = []
        for item in data:
            if item.lower() in fna_display_name:
                fna_item_index = fna_display_name.index(item.lower())
                sheet_id = fna[fna_item_index].id

                sheet = FnaSheet.objects.get(id=sheet_id)
                res = SheetData(sheet).get_count()

                final_sidebar.append({
                    'id': sheet_id,
                    'display_name': fna[fna_item_index].display_name,
                    'actual': res,
                    'target': 0,
                    'streek': 0
                })
            elif item.lower() in gm_display_name:
                gm_item_index = gm_display_name.index(item.lower())
                final_sidebar.append({
                    'id': gm[gm_item_index].id,
                    'display_name': gm[gm_item_index].display_name,
                    'actual': 0,
                    'target': 0,
                    'streek': 0
                })
            else:
                final_sidebar.append({
                    'id': 0,
                    'display_name': item,
                    'actual': 0,
                    'target': 0,
                    'streek': 0
                })
        sidebar_data_content[key] = final_sidebar

    context['sidebar_data'] = sidebar_data_content

    return context

gm_dashboard/views/dashboard.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import JsonResponse
from gm_dashboard.models import GMSheet, Sheet
from utils.sheets.process_sheets import ProcessSheets
from django.views.decorators.csrf import csrf_exempt

import time
import pdb

class DashboardIndexView(TemplateView):
    template_name = 'dashboard/index.html'
    def get(self, request):
        sheets = GMSheet.objects.all()
        context = {}
        context["sheets"] = sheets
        res = ProcessSheets().get_process_id()
        if res['status'] == 'running':
            context['running'] = res
        return render(request, self.template_name, context=context )

class SheetStatusView(TemplateView):
    def post(self, request):
        res = ProcessSheets().get_process_id()
        return JsonResponse(res, safe=False)

class RunSheetScriptView(TemplateView):
    def post(self, request, sheet):
        sheet =  GMSheet.objects.get(pk=sheet)
        if sheet:
            res = ProcessSheets().run_script(sheet)
            return JsonResponse(res, safe=False)

@csrf_exempt
def update_sheet(request):
    id = int(request.POST['id'])
    value = (request.POST['value'])
    sheet = Sheet.objects.filter(id=id).update(display_name=value)
    return JsonResponse(sheet, safe=False)

gm_dashboard/views/sheets.py
from django.shortcuts import render
from utils.server_db import query, csv_report_builder
from datetime import datetime
from gm_dashboard.models import GMSheet
from django.views.generic import TemplateView
from django.core import serializers
from django.http import HttpResponse
from gm_dashboard.forms.get_year_data import GetYearData
from pandas import read_csv
from utils.sheets.actual_vs_quoted import ActualVsQuoted
from utils.sheets.context import Context
from utils.sheets.process_sheets import ProcessSheets
import pdb
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
import numpy as np
import functools 
import json
from django.http import JsonResponse

class IndexView(TemplateView):
    def get(self, request, sheet):
        sheet = GMSheet.objects.get(id=sheet)
        context = Context(sheet).get_index_view_context()
        context["sheet"] = sheet
        return render(request, sheet.config_name + "/index.html", context=context )

class SummaryView(TemplateView):

    def get(self, request, sheet):
        GMSheet.objects.filter(id=sheet).update(updated_at=datetime.now())
        sheet = GMSheet.objects.get(id=sheet)
        context =  Context(sheet).get_summary_view_context()
        context["sheet"] = sheet
        return render(request, sheet.config_name + "/summary.html", context=context )
    
    def post(self, request, sheet):
        year = request.POST.get('year')
        data = ActualVsQuoted().get_specific_year_summary_data(year)
        return render(request, "partials/details_year_data.html", context={"key": year, "values" : data.items()} )


class Sheet1SummaryYearlyView(TemplateView):
    template_name = 'sheet1/yearly.html'
    
    def get(self, request, sheet, year):
        data = get_data_from_db_server()
        context = {}
        data = list(filter(lambda x: x[3] == int(year), data))
        context["result_years"] = data
        context["year"] = year
        return render(request, self.template_name, context=context )

def create_yearly_data(data):
    yearl_data = {}
    for row in data:
        if row[3] is not None:
            if row[3] in yearl_data.keys():
                if row[1] > 0:
                    yearl_data[row[3]]["actual"] = yearl_data[row[3]]["actual"] + row[1]
                if row[2] > 0:
                    yearl_data[row[3]]["quoted"] = yearl_data[row[3]]["quoted"] + row[2]
            else:
                yearl_data[row[3]] = {"actual": 0, "quoted": 0}
                if row[1] > 0:
                    yearl_data[row[3]]["actual"] = row[1]
                if row[2] > 0:
                    yearl_data[row[3]]["quoted"] = row[2]
    sorted_data = sort_yearly(yearl_data)
    
    return sorted_data

def get_winner(request, sheet):
    year = request.POST.get('year')
    data = ActualVsQuoted().get_winner_of_year(year)
    return render(request, "partials/get_leader_details.html", context={"values" : data.items()} )

def get_json_sheet(request, sheet):
    offset = int(request.GET['start'])
    limit = int(request.GET['length'])
    page = abs(int(offset/limit + 1))
    data = ActualVsQuoted().get_all_json(request)
    json_data = json.loads(data)
    length = len(json_data["data"])
    paginator = Paginator(json_data["data"], int(limit))
    objects = paginator.page(page)
    list_objs= list(objects)
    res = {
        "draw":  int(request.GET['draw']),
        "recordsTotal": length,
        "recordsFiltered": length,
        "data": list_objs,
    }
    return JsonResponse(res, safe=False)


def sort_yearly(data):
    sorted_data = {}
    for i in sorted(data, reverse=True): 
        sorted_data[i] = data[i]
        sorted_data[i]["ratio"] =round(data[i]["quoted"] / data[i]["actual"], 2)
    sorted_data.popitem()
    sorted_data.popitem()
    sorted_data.popitem()
    return sorted_data

def unique(list1):
    unique_list = []
    for x in list1:
        if x not in unique_list:
            unique_list.append(x)
    return unique_list

gm_dashboard/templates/dashboard/index.html
{% extends 'base.html' %}
{% load cache %}
{% load static %}
{% cache 500 content %}
{% block content %} 
<div class="row">
<div class="col-md-8">
    <div class="list list-row block">
        {% for sheet in sheets %}
        <div class="list-item row" data-id="19" id="showing_{{sheet.id}}">
            <div class="col-md-8">
                <div class="flex"> 
                    <a href="#" class="item-author text-color" data-abc="true">
                        {{sheet.display_name}}
                    </a>
                </div>
                <div class="no-wrap">
                    <div class="item-date text-muted text-sm d-none d-md-block">
                        {{sheet.updated_at}}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
            [
                <a href="{% url 'gm:sheet_summary' sheet.id %}" >View</a>
                ]
            </div>
        </div>
        <div class="list-item row" style="background:yellow; display: {{ a|yesno:"block,none" }}" data-id="19" id="loading_{{sheet.id}}" >
            <div class="col-md-8">
                <div class="flex"> 
                    <a href="#" class="item-author text-color" data-abc="true">
                        {{sheet.display_name}}
                    </a>
                </div>
                <div class="no-wrap">
                    <div class="item-date text-muted text-sm d-none d-md-block">
                        {{sheet.updated_at}}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
            [
                <a href="javascript:void(0);" onclick="alert('Please wait for the current action to finish.');return false;">View</a>
                ]
            </div>
        </div>
        {% endfor %}
    </div>
</div>
    <div class="form-group col-md-4">
        <form action="" id="filters_form">
            <label for="sheet">Select Sheet:</label>
            <select class="form-control" id="sheet">
                {% for sheet in sheets%}
                    <option value={{sheet.id}}>{{sheet.display_name}}</option>
                {% endfor %}
            </select>
            <div id="loading_td" style='display: {{running|yesno:"block,none"}}'>
                <img src="{% static 'assets/images/sheet_loading.gif'%}" alt="">
            </div>
            <div id="progress"></div>
            {% if running %}
                <input DISABLED id="compile_button" type="button" class="btn btn-primary w-100 mt-2" value="Recompile" onclick="clickOnCompileBtn()" />
            {% else %}
                <input id="compile_button" type="button" class="btn btn-primary w-100 mt-2" value="Recompile" onclick="clickOnCompileBtn()" />
            {% endif %}
        </form>
    </div>
</div>  
{% endblock %}
{% block js %}
    <script>
        var running = false;
        var clickOnCompileBtn = () => {
            if(confirm('Compiling the Sheet  may take a few minutes,\nso please be patient. Proceed?')){
                genSheet($("#sheet").val());
                return false;
            }
        }
        {% if running %} 
            running = true;
            checkSheetProgress('{{running.id}}');
        {% endif %}
        var to;
        function genSheet(id){
            if(running){
                alert('Please wait for the current action to finish.');
            } else {
                running = true;
                document.getElementById('compile_button').disabled = true;
                $('#showing_' + id).hide();
                $('#loading_' + id).show();
                $('#loading_td').show();
                var sheet = $("#sheet").val();
                $.ajax({
                    type: "POST",
                    headers: { "X-CSRFToken": '{{csrf_token}}' },
                    url: "/gm/dashboard/run_sheet_script/"+sheet,
                    dataType: "json",
                    success: function(r){
                        if(r.alert){
                        running = false;
                        alert(r.alert);
                        }
                    },
                    complete: function() {
                        if(running){
                        checkSheetProgress(id);
                        } else {
                        window.location.reload(); // only in case of error
                        }

                    }
                });
            }
        }
        function checkSheetProgress(id){
            if(to) clearTimeout(to);
            if(running) 
                to = setTimeout("updateSheetProgress('"+id+"');", 3000);
        }
        function updateSheetProgress(id){
            $.ajax({
                type: "POST",
                url: "/gm/dashboard/check_script_status",
                headers: { "X-CSRFToken": '{{csrf_token}}' },
                dataType: "json",
                success: function(r){
                    var id = r.sheet_id;
                    if(r.status == 'running'){
                        $('#showing_' + id).hide();
                        $('#loading_' + id).show();
                        $('#progress').html(r.elapsed);
                    } else {
                        running = false;
                        $('#progress').html('Done')
                        $('#showing_' + id).show();
                        $('#loading_' + id).hide();
                        document.getElementById('compile_button').disabled = false;
                        $('#loading_td').hide();
                    }
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                $('#loading').html('An error has occured. Please refresh the page.')
                },
                complete: function() {
                    if(running){
                        checkSheetProgress(id);
                    } else {
                        window.location.reload(); // only in case of error
                    }

                }
            });
        }
    </script>
{% endblock %}
{% endcache %}