FnA_dashboard/urls.py
from django.urls import path, include
from .views.sheets import update_follow_up_date, submit_pos, IndexView,update_r3_PO_LED, data_table_server_side, get_r3_PO_LED, get_r3d_PO_LED, update_department, select_primary_warehouse
from .views.dashboard import DepartmentDashboard, dashboard_datatable

app_name = "fna_urls"
urlpatterns = [
    path('sheets/<sheet>',IndexView.as_view()),
    path('sheets/<sheet>/datatable',data_table_server_side,name="server_side_table"),
    path('po_r3_leds/<po>',get_r3_PO_LED,name="po_r3_leds"),
    path('po_r3d_leds/<po>',get_r3d_PO_LED,name="po_r3d_leds"),
    path('update_r_3', update_r3_PO_LED, name="update_po_led"),
    path('submit_pos', submit_pos, name='submit_pos'),
    path('update_follow_up_date', update_follow_up_date, name='update_follow_up_date'),

    path('update_department', update_department, name='update_department'),
    path('dashboard/<department_name>', DepartmentDashboard.as_view(), name="department_dashboard"),
    path('select_primary_warehouse', select_primary_warehouse, name='select_primary_warehouse'),
    path('dashboard/datatable/<item_name>/<department_name>', dashboard_datatable, name="dashboard_server_side_table"),

]

clssite/urls.py
from django.contrib import admin
from django.urls import path , include
from .view import redirect_to_gm
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_gm),
    path('gm/',include(('gm_dashboard.urls','gm_dashboard'),namespace="gm") ),
    path('fna/',include(('FnA_dashboard.urls','FnA_dashboard'),namespace="fna") ),
]

FnA_dashboard/models.py
from django.db import models
from gm_dashboard.models import Sheet

# Create your models here.

class FnAManager(models.Manager):
  def get_queryset(self):
    return super().get_queryset().filter(sheet_type='FnA')

class FnaSheet(Sheet):
  objects = FnAManager()

  class Meta:
    proxy = True

FnA_dashboard/views/dasboard.py
from django.shortcuts import render
from FnA_dashboard.models import FnaSheet
from django.views.generic import TemplateView
from FnA_dashboard.utils.sheet_data  import SheetData
import pdb
from  utils.server_db import query, update_query
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime
import json
from utils.department.department_info import read_write_department, Department_Data

class DepartmentDashboard(TemplateView):
    def get(self, request, department_name):
        context = {}
        sidebar_data = Department_Data(department_name).get_headers()
        context["columns"] = columns
        context["columns_len"] = range(0,len(columns))
        try:
            return render(request, sheet.code + "/index.html", context=context )
        except:
            return render(request,  "index.html", context=context )


def department_dashboard(department_name):
    context = {}
    sidebar_data = Department_Data(department_name)
    context["headers"], sidebar_data_content, context["department_name"] = sidebar_data.get_sidebar()

    fna = fna_sheets(request)['fna_sheets']
    gm = gm_sheets(request)['gm_sheets']

    fna_display_name = list(fna.values_list('display_name', flat=True))
    fna_display_name = [x.lower() for x in fna_display_name]

    gm_display_name = list(gm.values_list('display_name', flat=True))
    gm_display_name = [x.lower() for x in gm_display_name]

    for key, data in sidebar_data_content.items():
        final_sidebar = []
        for item in data:
            if item.lower() in fna_display_name:
                fna_item_index = fna_display_name.index(item.lower())
                sheet_id = fna[fna_item_index].id

                sheet = FnaSheet.objects.get(id=sheet_id)
                res = SheetData(sheet).get_count()

                final_sidebar.append({
                    'id': sheet_id,
                    'display_name': fna[fna_item_index].display_name,
                    'actual': res,
                    'target': 0,
                    'streek': 0
                })
            elif item.lower() in gm_display_name:
                gm_item_index = gm_display_name.index(item.lower())
                final_sidebar.append({
                    'id': gm[gm_item_index].id,
                    'display_name': gm[gm_item_index].display_name,
                    'actual': 0,
                    'target': 0,
                    'streek': 0
                })
            else:
                final_sidebar.append({
                    'id': 0,
                    'display_name': item,
                    'actual': 0,
                    'target': 0,
                    'streek': 0
                })
        sidebar_data_content[key] = final_sidebar

    context['sidebar_data'] = sidebar_data_content

    return context

FnA_dashboard/views/dashboard.py
from django.shortcuts import render
from FnA_dashboard.models import FnaSheet
from django.views.generic import TemplateView
from FnA_dashboard.utils.sheet_data  import SheetData
import pdb
from  utils.server_db import query, update_query
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime
import json
from utils.department.department_info import read_write_department, Department_Data
from gm_dashboard.context_processors import fna_sheets, gm_sheets
from django.core.paginator import Paginator
from utils.server_db import query

class DepartmentDashboard(TemplateView):
    def get(self, request, department_name):
        context = {}
        columns = Department_Data(department_name).get_headers()
        # context["columns"] = columns
        # context["columns_len"] = range(0,len(columns))
        
        context["columns"] = {}
        for c in columns:
            context["columns"][c] = dashboard_datatable(request, c, department_name)

        return render(request, "dashboard.html", context=context )


class DatatableClass():
    def __init__(self, id, name, actual):
        self.id = id
        self.name = name
        self.actual = actual

    def get_obj(self):
        return self


def format_datatable_request(datatables):
    request = {}
    request["draw"] = int(datatables.get('draw')) if datatables.get('draw') else ''
    request["start"] = int(datatables.get('start')) if datatables.get('start') else ''
    request["total"] = int(datatables.get('length')) if datatables.get('length') else ''
    request["ordercol"] = int(datatables.get('order[0][column]')) if datatables.get('order[0][column]') else ''
    request["order"] = datatables.get('order[0][dir]') if datatables.get('order[0][dir]') else ''
    request["reverse"] = request["order"] == "asc"
    return request


def ordering_datatable_response(order_list, formatted_req, request):
    # members_order_list = order_list

    formatted_req["total"] = len(order_list) if formatted_req["total"] == -1 else formatted_req["total"]

    filtered_count = len(order_list)

    # members_order_list = sort_datatable_data(members_order_list, formatted_req, 1, ORDER_COLS_MEMBERS_LISTING)

    members_order_list = order_list[formatted_req["start"]:formatted_req["start"] + formatted_req["total"]]
    paginator = Paginator(members_order_list, formatted_req["total"])
    return [paginator, filtered_count]


def response_dump(paginator, start, draw, total_uses):
    try:
        data = paginator.page(0).object_list
    except:
        data = paginator.page(1).object_list
    resp = {
        "draw": draw,
        "recordsTotal": total_uses,
        "recordsFiltered": total_uses,
        "data": list(data)
    }
    return resp


def dashboard_datatable(request, item_name, department_name):
    context = {}
    columns_name = Department_Data(department_name).get_items(item_name)
    fna = fna_sheets(request)['fna_sheets']
    gm = gm_sheets(request)['gm_sheets']

    fna_display_name = list(fna.values_list('display_name', flat=True))
    fna_display_name = [x.lower() for x in fna_display_name]

    gm_display_name = list(gm.values_list('display_name', flat=True))
    gm_display_name = [x.lower() for x in gm_display_name]
    
    final_list = []
    for item in columns_name:
        if item.lower() in fna_display_name:
            fna_item_index = fna_display_name.index(item.lower())
            sheet_id = fna[fna_item_index].id

            sheet = FnaSheet.objects.get(id=sheet_id)
            res = SheetData(sheet).get_count()
            res = query(res)[0][0]
            # obj = DatatableClass(sheet_id, fna[fna_item_index].display_name, res)
            # final_list.append(obj.get_obj())
            final_list.append({
                'id': sheet_id,
                'display_name': fna[fna_item_index].display_name,
                'actual': res,
                'target': 0,
                'streek': 0
            })

        elif item.lower() in gm_display_name:
            gm_item_index = gm_display_name.index(item.lower())
            final_list.append({
                'id': gm[gm_item_index].id,
                'display_name': gm[gm_item_index].display_name,
                'actual': 0,
                'target': 0,
                'streek': 0
            })
        else:
            final_list.append({
                'id': 0,
                'display_name': item,
                'actual': 0,
                'target': 0,
                'streek': 0
            })

    return final_list

    # formatted_req = format_datatable_request(request.GET)
    # paginator, filtered_count = ordering_datatable_response(final_list, formatted_req, request)
    # return JsonResponse(response_dump(paginator, formatted_req["start"], formatted_req["draw"], filtered_count))


def department_dashboard(department_name):
    context = {}
    sidebar_data = Department_Data(department_name)
    context["headers"], sidebar_data_content, context["department_name"] = sidebar_data.get_sidebar()

    fna = fna_sheets(request)['fna_sheets']
    gm = gm_sheets(request)['gm_sheets']

    fna_display_name = list(fna.values_list('display_name', flat=True))
    fna_display_name = [x.lower() for x in fna_display_name]

    gm_display_name = list(gm.values_list('display_name', flat=True))
    gm_display_name = [x.lower() for x in gm_display_name]

    for key, data in sidebar_data_content.items():
        final_sidebar = []
        for item in data:
            if item.lower() in fna_display_name:
                fna_item_index = fna_display_name.index(item.lower())
                sheet_id = fna[fna_item_index].id

                sheet = FnaSheet.objects.get(id=sheet_id)
                res = SheetData(sheet).get_count()

                final_sidebar.append({
                    'id': sheet_id,
                    'display_name': fna[fna_item_index].display_name,
                    'actual': res,
                    'target': 0,
                    'streek': 0
                })
            elif item.lower() in gm_display_name:
                gm_item_index = gm_display_name.index(item.lower())
                final_sidebar.append({
                    'id': gm[gm_item_index].id,
                    'display_name': gm[gm_item_index].display_name,
                    'actual': 0,
                    'target': 0,
                    'streek': 0
                })
            else:
                final_sidebar.append({
                    'id': 0,
                    'display_name': item,
                    'actual': 0,
                    'target': 0,
                    'streek': 0
                })
        sidebar_data_content[key] = final_sidebar

    context['sidebar_data'] = sidebar_data_content

    return context

FnA_dashboard/views/sheets.py
from django.shortcuts import render
from FnA_dashboard.models import FnaSheet
from django.views.generic import TemplateView
from FnA_dashboard.utils.sheet_data  import SheetData
import pdb
from  utils.server_db import query, update_query
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime
import json
from utils.department.department_info import read_write_department, Department_Data
from utils.r8.R8_info import read_write_warehouse
import environ
env = environ.Env()

class IndexView(TemplateView):
    def get(self, request, sheet):
        print(sheet)
        if sheet == '0':
            return render(request,  "coming_soon.html")

        context = {}
        FnaSheet.objects.filter(id=sheet).update(updated_at=datetime.now())
        sheet = FnaSheet.objects.get(id=sheet)
        columns = SheetData(sheet).get_headers()
        context["sheet"] = sheet
        context["columns"] = columns
        context["columns_len"] = range(0,len(columns))
        try:
            return render(request, sheet.code + "/index.html", context=context )
        except:
            return render(request,  "index.html", context=context )

def data_table_server_side(request, sheet):
    sheet = FnaSheet.objects.get(id=sheet)
    res = SheetData(sheet).get_table(request)
    return JsonResponse(res, safe=False)


def get_r3_PO_LED(request, po):
    sql = f"SELECT POLed.[Part], POLed.[Desc], POLed.[Quan], POLed.[Price], POLed.[Amount] FROM POLed WHERE POLed.[PO] = '{po}'"
    result = query(sql)
    res = []
    for row in result:
        res.append(list(row))
    return JsonResponse(res, safe=False)

@csrf_exempt
def update_r3_PO_LED(request):
    attr =  request.POST.get('attribute')
    value = request.POST.get('value')
    part =  request.POST.get('part')
    po =  request.POST.get('po')
    sql_query = f"UPDATE POLed SET {attr} = '{value}' WHERE POLed.[Part] = '{part}' AND POLed.[PO] = '{po}'"
    update_query(sql_query)
    return JsonResponse({}, safe=False)


def get_r3d_PO_LED(request, po):
    sql = f"SELECT POLed.[Part], POLed.[Desc], POLed.[Quan] FROM POLed WHERE POLed.[PO] = '{po}'"
    result = query(sql)
    res = []
    for row in result:
        res.append(list(row))
    return JsonResponse(res, safe=False)

def submit_pos(request):
    pos =  request.POST.get('POS', False)
    data = tuple(json.loads(pos))
    sql_pos  = data if len(data) > 1  else f"('{data[0]}')"
    sql_query = f"UPDATE PO SET OrderPlaced = '-1' WHERE PO.[PO] IN {sql_pos}"
    update_query(sql_query)
    return JsonResponse({"success": True}, safe=False)

def select_primary_warehouse(request):
    pos =  request.POST.get('POS', False)
    data = str(pos)
    # data = dict(data)
    # with open(env('STORAGE_DIR')+"warehouses.yml", 'w') as outfile:
    #         yaml.dump(data, outfile, default_flow_style=False)
    print(data)
    read_write_warehouse(data,True)
    return JsonResponse({"success": True}, safe=False)

def update_follow_up_date(request):
    po = request.POST.get("po")
    folow_up_date = request.POST.get("followUpDate")
    sql = f"UPDATE PO SET DateReq='{folow_up_date}' WHERE PO.[PO] = '{po}'"
    update_query(sql)
    return JsonResponse({"success": True , "msg": f"Successfully Updated {po} PO's Follow up Date"}, safe=False)


def update_department(request):
    if request.POST:
        department = request.POST.get("department_name")
        read_write_department(department=department, is_write=True)

        return JsonResponse({
            "success": True
        })

FnA_dashboard/templates/R-3/index.html
{% extends 'base.html' %}
{% load cache %}
{% load static %}
{% cache 500 content %}
{% block content %} 
<style>
    .active{
        background-color:#1F4E78 !important;
        color: white;
    }
</style>
<div class="d-flex mb-3 mb-md-4 justify-content-between">
    <h4 class=" sheet_link" data-id="{{sheet.id}}">{{sheet.display_name}}</h4> 
</div>

   <table class="table table-cls table-bordered" id="po">
       <thead><tr>
           {% for c in columns%}
           <th>{{c}}</th>
           {% endfor %}
           <th><input type="checkbox" name="id[]" id="po-select-all"></th>
       </tr></thead>
       <tbody></tbody>
  </table>
{% endblock %}

{% block js %}
<script>
    var poSubmissionArray = []

    var url = "{% url 'fna:server_side_table' sheet.id %}"
    var submitPosUrl = "{%url 'fna:submit_pos'%}"
    var token = '{{csrf_token}}';

    var editableColumns = () =>{ 
        $(".po-edit-int").each(function() {
            var attribute = $(this).data("attribute")
            var part = $(this).data("part")
            var po = $(this).data("po")
            $(this).editable({
                event :'click',
                touch :true,
                emptyMessage :false,
                url: '/fna/update_r_3',
                type: 'number',
                step: 'any',
                placement: "top",
                pk: 1,
                name: 'display_name',
                params: function(params) {
                    params["X-CSRFToken"] = token
                    params['part'] = part;
                    params['po'] = po;
                    params['attribute'] = attribute;
                    return params;
                },
                // success: function(response, newValue) {
                //     window.location.reload()
                // },
                validate: function(value) {
                    if($.trim(value) == '') {
                        return 'This field is required';
                    }
                }
            });    
        });
    
    }

    $(document).ready(()=>{
        var editableFields =  () => {
            $(".editable").each(function() {
                var current_element = $(this);
                var id = $(this).data("id")
                $(this).editable({
                    event :'click',
                    touch :true,
                    emptyMessage :false,
                    url: '/gm/update_sheet',
                    type: 'text',
                    pk: 1,
                    name: 'display_name',
                    params: function(params) {
                        params['id'] = id;
                        return params;
                    },
                    success: function(response, newValue) {
                    window.location.reload()
                    },
                    validate: function(value) {
                        if($.trim(value) == '') {
                            return 'This field is required';
                        }
                    }
                });    
            });
        }
        $('#po thead tr').clone(true).appendTo( '#po thead' );
        $('#po thead tr:eq(0) th').each( function (i) {
            var title = $(this).text();
            if(title != ""){
                $(this).html( '<input type="text" placeholder="Search '+title+'"   id="'+title.split(' ').join('_')+'"/>' );
            }else{
                var html = ""
                $(this).html("<button class='btn btn-primary' id='submitPOs' disabled>Submit</button")
            }
            $( 'input', this ).on( 'keyup change', function () {
                if ( table.column(i).search() !== this.value ) {
                    table
                        .column(i)
                        .search( this.value )
                        .draw();
                }
            } );
        } );

        var editableFields =  () => {
            $(".editable").each(function() {
                var current_element = $(this);
                var id = $(this).data("id")
                $(this).editable({
                    event :'click',
                    touch :true,
                    emptyMessage :false,
                    url: '/gm/update_sheet',
                    type: 'text',
                    pk: 1,
                    name: 'display_name',
                    params: function(params) {
                        params['id'] = id;
                        return params;
                    },
                    success: function(response, newValue) {
                    window.location.reload()
                    },
                    validate: function(value) {
                        if($.trim(value) == '') {
                            return 'This field is required';
                        }
                    }
                });    
            });
        }
      
        var table = $('#po').DataTable({
                    processing: true,
                    serverSide: true,
                    select: {
                        style:    'os',
                        selector: 'td:first-child'
                    },
                    "ajax": {
                        url: url,
                        type: "GET",
                    },
                    
                               
                    'columnDefs': [{
                        'targets': 3,
                        'searchable': false,
                        'orderable': false,
                        'className': 'dt-body-center',
                        'render': function (data, type, full, meta){
                            return '<input type="checkbox" name="id[]" value="' + (full[0]) + '">';
                        }
                    }],
                    columns: [
                        {data: 0},
                        {data: 1},
                        {data: 2},
                    ],
                    createdRow: function(row, data, index) {
                        $(row).addClass("inner-content");
                        $(row).attr('id', $.trim(data[0]))
                        $(row).attr('data-id', $.trim(data[0]))
                        $(row).find('td:eq(2)').attr("data-column-name",)
                        $("#po-select-all").prop("checked", false)
                        
                    },
                    drawCallback:  settings => {
                        poSubmissionArray = []
                        displaySubmitBtn()
                        setTimeout(selectSelectedFilters, 500)
                        setTimeout(checkBoxes, 500)
                    }

                });
                var checkBoxes = ()=>{
                    $("input[name='id[]']").on('change',e => {
                        poSubmissionArray = []
                        table.$('input[type="checkbox"]').each(function(){
                            // If checkbox doesn't exist in DOM
                                // If checkbox is checked
                                if(this.checked){
                                    poSubmissionArray.push(this.value)
                                }else{
                                    const index = poSubmissionArray.indexOf(this.value);
                                    if (index > -1) {
                                        poSubmissionArray.splice(index, 1);
                                    }
                                }
                        });
                        displaySubmitBtn()
                    })
                }
                var displaySubmitBtn = ()  => {
                    if(poSubmissionArray.length != 0){
                        $("#submitPOs").attr('disabled', false)
                    }else{
                        $("#submitPOs").attr('disabled', true)
                    }
                }
                $("#submitPOs").on("click", function() {
                    
                    $.ajax({
                        headers: { "X-CSRFToken": token },
                        url: submitPosUrl,
                        type: 'POST',
                        data: {"POS": JSON.stringify(poSubmissionArray) },
                        success: res => {
                            showSuccessMsg(`Submiting Following POS: ${poSubmissionArray}`)
                            table.ajax.reload( null, false );
                        },
                        error: err => {

                        }
                    })

                })
                
                function format ( d ) {
                    var id = d[0].split(' ').join('_')
                    var html = `<div style="position: relative;">
                            <table cellpadding="5"  cellspacing="0" class=' offlineTable w-100 table-cls table-bordered'>
                            <thead>
                                <tr>
                                    <th>Part</th>
                                    <th>Desc</th>
                                    <th>Quan</th>
                                    <th>Price</th>
                                    <th>Amount</th>
                                </tr>
                            </thead>
                            <tbody id='tbody${id}'>`
                                html+= `<tr><td colspan="5" class="text-center"><div class="spinner-border text-secondary" role="status">
                                        <span class="sr-only">Loading...</span>
                                        </div></td></tr>
                                    </tbody></table>
                                    <div class="close-table-btn" id="close-btn${$.trim(d[0])}"  data-id="${id}">x</div>
                                    </div>`

                    $.ajax({
                        url: "/fna/po_r3_leds/"+$.trim(d[0]),
                        success: res => {
                            $("#tbody"+id).empty()
                            if(res.length == 0){
                                var rowHtml = `<tr>
                                    <td colspan="5" class="text-center">
                                    No Item found
                                    </td>
                                </tr>
                                    `;
                                $("#tbody"+id).append(rowHtml);
                            }
                            res.forEach(element => {
                                var rowHtml =  `<tr>
                                        <td>${element[0]}</td>
                                        <td>${element[1]}</td>
                                        <td class='po-edit-int' data-attribute='POLed.[Quan]' data-part='${element[0]}' data-po='${$.trim(d[0])}'>${element[2]}</td>
                                        <td class='po-edit-int' data-attribute='POLed.[Price]' data-part='${element[0]}' data-po='${$.trim(d[0])}'>${element[3]}</td>
                                        <td class='po-edit-int'  data-attribute='POLed.[Amount]' data-part='${element[0]}' data-po='${$.trim(d[0])}'>${element[4]}</td>
                                    </tr>`;
                                $("#tbody"+id).append(rowHtml);
                            });
                            editableColumns()
                        },
                    })
                    return html
                }
        
        // Add event listener for opening and closing details
        $('#po tbody').on('dblclick', 'tr.inner-content', function () {
            var tr = $(this);
            var row = table.row( tr );
            var id =  tr.attr("id")
            if ( row.child.isShown() ) {
                // This row is already open - close it
                row.child.hide();
                tr.removeClass('shown');
                tr.removeClass('active');
            }
            else {
                // Open this row
                var res = format(row.data())
                row.child( res, ' p-0' ).show();
                tr.addClass('shown');
                tr.addClass('active');
                
                
            }
            $("#close-btn"+id).on('click', e => {
                    var tr = $("#"+id)
                    var row = table.row(tr)
                    row.child.hide();
                    tr.removeClass('shown');
                    tr.removeClass('active');
                })
                
        } );


       $("#po_filter").empty()
       $('#po-select-all').on('click', function(){
            // Get all rows with search applied
            var rows = table.rows({ 'search': 'applied' }).nodes();
            // Check/uncheck checkboxes for all rows in the table
            $('input[type="checkbox"]', rows).prop('checked', this.checked);
        });
       var selectSelectedFilters = () => {
            var vars = {};
            var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value) {
                vars[key] = value;
            });
            for (var key in vars) {
                if (vars.hasOwnProperty(key)) {
                        $("#"+key).val(vars[key]);
                        $("#"+key).trigger("change");
                }
            }
       }  
    })
</script>
{% endblock %}
{% endcache %}