FnA_dashboard/urls.py
from django.urls import path, include
from .views.sheets import update_follow_up_date, submit_pos, IndexView,update_r3_PO_LED, data_table_server_side, get_r3_PO_LED, get_r3d_PO_LED, update_department, select_primary_warehouse
from .views.dashboard import DepartmentDashboard, dashboard_datatable

app_name = "fna_urls"
urlpatterns = [
    path('sheets/<sheet>',IndexView.as_view()),
    path('sheets/<sheet>/datatable',data_table_server_side,name="server_side_table"),
    path('po_r3_leds/<po>',get_r3_PO_LED,name="po_r3_leds"),
    path('po_r3d_leds/<po>',get_r3d_PO_LED,name="po_r3d_leds"),
    path('update_r_3', update_r3_PO_LED, name="update_po_led"),
    path('submit_pos', submit_pos, name='submit_pos'),
    path('update_follow_up_date', update_follow_up_date, name='update_follow_up_date'),

    path('update_department', update_department, name='update_department'),
    path('dashboard/<department_name>', DepartmentDashboard.as_view(), name="department_dashboard"),
    path('select_primary_warehouse', select_primary_warehouse, name='select_primary_warehouse'),
    path('dashboard/datatable/<item_name>/<department_name>', dashboard_datatable, name="dashboard_server_side_table"),

]

clssite/urls.py
from django.contrib import admin
from django.urls import path , include
from .view import redirect_to_gm
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_gm),
    path('gm/',include(('gm_dashboard.urls','gm_dashboard'),namespace="gm") ),
    path('fna/',include(('FnA_dashboard.urls','FnA_dashboard'),namespace="fna") ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/jpg" href="{% static '/assets/images/fav.jpg' %}"/>
    <title>index</title>
    <link rel="stylesheet" href="{% static '/assets/vendors/core/core.css' %}">
    <link rel="stylesheet" href="{% static '/assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css' %}">
    <link rel="stylesheet" href="{% static '/assets/fonts/feather-font/css/iconfont.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css">
    {% block headtag %}
    {% endblock %}
</head>
<body class="sidebar-dark">
<div class="main-wrapper">
    {% include 'partials/sidebar.html' %}

    <div class="page-wrapper">
        {% include 'partials/topbar.html' %}

        <div class="page-content">

            <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
                <div class="w-100">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>

        </div>

        <!-- partial:partials/_footer.html -->

        <!-- partial -->

    </div>
</div>
<div>
    <div id="loading"></div>
</div>
<script src="{% static '/assets/vendors/core/core.js' %}"></script>
<script src="{% static '/assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static '/assets/vendors/feather-icons/feather.min.js' %}"></script>
<script src="{% static '/assets/js/template.js' %}"></script>
<script src="{% static '/assets/js/dashboard.js' %}"></script>
<script src="{% static '/assets/js/datepicker.js' %}"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.css"
      integrity="sha512-8D+M+7Y6jVsEa7RD6Kv/Z7EImSpNpQllgaEIQAtqHcI0H6F4iZknRj0Nx1DCdB+TwBaS+702BGWYC0Ze2hpExQ=="
      crossorigin="anonymous"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js"
        integrity="sha512-zlWWyZq71UMApAjih4WkaRpikgY9Bz1oXIW5G0fED4vk14JjGlQ1UmkGM392jEULP8jbNMiwLWdM8Z87Hu88Fw=="
        crossorigin="anonymous"></script>
<script src='https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js'></script>
<script src='https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js'></script>
<link href="https://cdn.jsdelivr.net/gh/Talv/x-editable@develop/dist/bootstrap4-editable/css/bootstrap-editable.css"
      rel="stylesheet">
<link href="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.css" rel="stylesheet">

<script src="https://cdn.jsdelivr.net/gh/Talv/x-editable@develop/dist/bootstrap4-editable/js/bootstrap-editable.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.15.4/dist/extensions/editable/bootstrap-table-editable.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js"
        integrity="sha512-RCgrAvvoLpP7KVgTkTctrUdv7C6t7Un3p1iaoPr1++3pybCyCsCZZN7QEHMZTcJTmcJ7jzexTO+eFpHk4OCFAg=="
        crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.css"
      integrity="sha512-YdYyWQf8AS4WSB0WWdc3FbQ3Ypdm0QCWD2k4hgfqbQbRCJBEgX0iAegkl2S1Evma5ImaVXLBeUkIlP6hQ1eYKQ=="
      crossorigin="anonymous"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
      integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
      crossorigin="anonymous"/>
<script>
    var showSuccessMsg = (msg) => {
        $.toast({
            text: msg,
            showHideTransition: 'fade',
            allowToastClose: true,
            hideAfter: 5000,
            loader: false,
            loaderBg: '#9EC600',
            position: 'top-right',
            bgColor: '#28a745',
            textColor: '#eee',
            textAlign: 'left',
            icon: false,
        })
    }
    $(document).ready(function () {
        $("#loading").hide()
        $(".sheet_link").each(function () {
            var current_element = $(this);
            var id = $(this).data("id")
            $(this).editable({
                event: 'dblclick',
                touch: true,
                emptyMessage: false,
                url: '/gm/update_sheet',
                type: 'text',
                pk: 1,
                name: 'display_name',
                params: function (params) {
                    params['id'] = id;
                    return params;
                },
                success: function (response, newValue) {
                    window.location.reload()
                },
                validate: function (value) {
                    if ($.trim(value) == '') {
                        return 'This field is required';
                    }
                }
            });
        });
    })
</script>
{% block js %}
{% endblock %}

</body>

</html>
<script>
    $(document).ready(function () {
        $('.nav-link, .collapsed').click();
        $('#id_department_change option[value={{ department_name }}]').prop('selected', 'selected');
    });
    $("#id_department_change").change(function () {
            var end = this.value;
            var firstDropVal = $('#id_department_change option:selected').text();
            var token = '{{csrf_token}}';
            $.ajax({
                headers: { "X-CSRFToken": token },
                url: "/fna/update_department",
                type: "POST",
                data: {"department_name": firstDropVal},
                success: res => {
                    if (res["success"]){
                        window.location = '{% url "fna_urls:department_dashboard" department_name=1234 %}'.replace(/1234/, firstDropVal);
                    }
                }
            })
    });
</script>
 

templates/home.html
{% extends 'base.html' %}
{% load cache %}
{% load static %}
{% cache 500 content %}
{% block content %}
   <h1>hello world</h1>

{% endblock %}
{% endcache %}